gameDirectory = ~/.local/share/rock-core-launcher/game
protonPath = ~/.local/share/rock-core-launcher/runner
winePrefix = ~/.local/share/rock-core-launcher/wineprefix
steamPath = ~/.steam/steam
verboseLogs = true
runtimeUpdate = true
gameId = umu-default
gameDownloadUrl = https://github.com/bubbles-wow/mcbe-gdk-unpack-archive
